set nocompatible
set noswapfile
filetype off
syntax on
set incsearch
set hlsearch
set noignorecase
set number
set shiftwidth=4
set tabstop=4
set noexpandtab
set enc=utf-8
set autoindent
set smartindent
setlocal cm=blowfish2
" disable F1 help key, map it to esc
nmap <F1> <nop>
map <F1> <Esc>
imap <F1> Esc>

"For autocompleting braces or brackets. I prefer to leave this off
"inoremap {<CR>  {<CR>}<Esc>O
"inoremap {}     {}

"only scroll one terminal line at a time, regardless of wrapping
noremap j gj
noremap k gk

"Useful tab nagigating stuff
nnoremap <Space>t :tabnew 
nnoremap <Space>h :tabprev<cr>
nnoremap <Space>l :tabnext<cr>
nnoremap <Space>w :w<cr>
nnoremap <Space>x :x<cr>

"Make tabs look good, show trailing whitespace
set listchars=tab:▒░,trail:-
"set listchars=tab:,trail:-
set list
hi SpecialKey ctermfg=darkgrey

set cursorline
"set cursorcolumn
hi CursorLine   cterm=bold ctermbg=darkgrey ctermfg=none
hi CursorColumn cterm=bold ctermbg=none ctermfg=none

"anything over the 80 character limit should be underlined
hi OverLength term=underline cterm=underline
match OverLength /\%81v.\+/

" Enable searching for files in subdirectories
set path+=**
set wildmenu

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')
"

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'scrooloose/syntastic'
Plugin 'kien/rainbow_parentheses.vim'
call vundle#end()            " required

if has("autocmd")
	au BufReadPost *.rkt,*.rktl set filetype=racket
	au filetype racket set lisp
	au filetype racket set autoindent
endif

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_racket_checkers = ['racket']
let g:syntastic_mode_map = {
    \ "mode": "active",
    \ "passive_filetypes": ["java"] }
let g:rbpt_colorpairs = [
    \ ['brown',       'RoyalBlue3'],
    \ ['Darkblue',    'SeaGreen3'],
    \ ['darkgray',    'DarkOrchid3'],
    \ ['darkgreen',   'firebrick3'],
    \ ['darkcyan',    'RoyalBlue3'],
    \ ['darkred',     'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['brown',       'firebrick3'],
    \ ['gray',        'RoyalBlue3'],
    \ ['black',       'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['Darkblue',    'firebrick3'],
    \ ['darkgreen',   'RoyalBlue3'],
    \ ['darkcyan',    'SeaGreen3'],
    \ ['darkred',     'DarkOrchid3'],
    \ ['red',         'firebrick3'],
    \ ]
let g:rbpt_max = 16
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces
